---

- include: docker_engine_debian.yml
  when: ansible_os_family == 'Debian'

- include: docker_engine_redhat.yml
  when: ansible_os_family == 'RedHat'
    and ansible_distribution != 'Amazon'

- name: Install Docker dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Remove old docker versions.
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  when: remove_old_versions

- name: Install the Docker Engine.
  package:
    name: docker-ce
    state: present
  when: ansible_distribution != 'Amazon'

- name: Install the Docker Engine (Amazon Linux)
  package:
    name: docker
    state: present
  when: ansible_distribution == 'Amazon'

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: started
    enabled: yes
