---

- include: docker_engine_debian.yml
  when: ansible_os_family == 'Debian'

- include: docker_engine_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Install the Docker Engine.
  package:
    name: docker-ce
    state: present

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: started
    enabled: yes
